### ISSUE TITLE
Question about twine's future in respect to Polaris?

### ISSUE THREAD

**Issue by chrismanderson** [Shopify/twine#94]
Howdy! With you all having rolled out [Polaris](https://polaris.shopify.com), I'm curious if you'll still be issuing Twine updates or if this sort of work will be focus in Polaris instead.

Thanks.

**Comment by pushrax** [comment]
Twine has always been intended to be a simple, single-purpose library, so to be honest it probably shouldn't have more features than it does. For a while there has been very little work done on Twine, mostly because there doesn't need to be any. PRs for bugfixes will be reviewed and accepted for sure, but it's unlikely that there will be any performance enhancements or features added.

**Comment by chrismanderson** [comment]
Makes sense; thanks for the info.
